/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aegs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    Connection con;
    Statement st;
    ResultSet rs;
    ArrayList<String []> row;
    
    public Login() {
        initComponents();
        initDb();
        addStudent();
    }

    private void addStudent()
    {
        try {
            row = new ArrayList<>();
            String [] record;
            rs = st.executeQuery("Select matric, password From student");
            
            while(rs.next())
            {
                record = new String[2];
                record[0] = rs.getString(1);
                record[1] = rs.getString(2);
                row.add(record);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Course.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initDb() {
        try {
            new Database();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AEGS", "root", "");
            st = con.createStatement();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error Connecting to the Database\nConnect the DBMS and run the application again!");
            System.exit(0);
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_panel = new javax.swing.JPanel();
        login_mode = new javax.swing.JComboBox();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        reset = new javax.swing.JButton();
        login = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        display = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1100, 530));
        setMinimumSize(new java.awt.Dimension(1100, 530));

        login_panel.setBackground(new java.awt.Color(0, 153, 255));
        login_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Page", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        login_panel.setMaximumSize(new java.awt.Dimension(330, 530));
        login_panel.setMinimumSize(new java.awt.Dimension(330, 530));
        login_panel.setPreferredSize(new java.awt.Dimension(330, 530));

        login_mode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Login Mode", "Examiner Login", "Student Login" }));
        login_mode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                loginMode(evt);
            }
        });

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Username");

        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginToPage(evt);
            }
        });

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginToPage(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginToPage(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginToPage(evt);
            }
        });

        error.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout login_panelLayout = new javax.swing.GroupLayout(login_panel);
        login_panel.setLayout(login_panelLayout);
        login_panelLayout.setHorizontalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username)
                            .addComponent(password)))
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(login_mode, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(reset)
                                .addGap(18, 18, 18)
                                .addComponent(login)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        login_panelLayout.setVerticalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(login_mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(password)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(login))
                .addGap(18, 18, 18)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        display.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aegs/images/display.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginToPage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginToPage
        // TODO add your handling code here:
        if(evt.getSource() == reset)
        {
            username.setText("");
            password.setText("");
            login_mode.setSelectedIndex(0);
        }
        else //if(evt.getSource() == login)
        {
            if(!(login_mode.getSelectedIndex() == 0))
            {
                if(!(username.getText().equals("") || password.getText().equals("")))
                {
                    if(login_mode.getSelectedIndex() == 1)
                    {
                        if(username.getText().equalsIgnoreCase("examiner"))
                        {
                            if(password.getText().equalsIgnoreCase("12345"))
                            {
                                //login to admin page
                                Frame.container.removeAll();
                                Frame.container.add(new Examinar());
                                Frame.container.repaint();
                                Frame.container.revalidate();
                                
                            }else
                                error.setText("Invalid Password");
                        }else
                            error.setText("Invalid Username");
                    }else if(login_mode.getSelectedIndex() == 2)
                    {
                        for (String[] row1 : row) {
                            if (row1[0].equalsIgnoreCase(username.getText()) && row1[1].equalsIgnoreCase(password.getText())) {
                                //login to student page
                                Frame.container.removeAll();
                                Frame.container.add(new Student(username.getText()));
                                Frame.container.repaint();
                                Frame.container.revalidate();
                                break;
                            }
                        }
                        error.setText("Invalid Username &/ Password");
                    }
                }
                else
                    error.setText("Enter Username and Password");
            }
            else
                error.setText("Select a valid Login mode");
        }
    }//GEN-LAST:event_loginToPage

    private void loginMode(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_loginMode
        // TODO add your handling code here:
        error.setText("");
        if(login_mode.getSelectedIndex() == 1)
        {
            user.setText("Examiner Username:");
            pass.setText("Examiner Password:");
        }
        else if(login_mode.getSelectedIndex() == 2)
        {
            user.setText("Student Username:");
            pass.setText("Student Password:");
        }
        else
        {
            user.setText("Username:");
            pass.setText("Password:");
        }
    }//GEN-LAST:event_loginMode


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel display;
    private javax.swing.JLabel error;
    private javax.swing.JButton login;
    private javax.swing.JComboBox login_mode;
    private javax.swing.JPanel login_panel;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JLabel user;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
